/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import static database.databaseConnection.getConnection;
import static frames.home.userName;;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Beatrice Antoniu - w1688177
 */
public class adminPanel extends javax.swing.JInternalFrame {

    /**
     * Creates new form adminPanel
     *
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public adminPanel() throws SQLException, ClassNotFoundException {
        initComponents();
    }
    //calling the decoding method
    private static String getDecodedPassword(String password) {
        return new String(Base64.getMimeDecoder().decode(password));
    }
    //calling the encoding method
    private static String getEncodedPassword(String password) {
        return Base64.getEncoder().encodeToString(password.getBytes());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminPanel = new javax.swing.JPanel();
        changePassword = new javax.swing.JPanel();
        passwordIcon = new javax.swing.JLabel();
        passwordText = new javax.swing.JLabel();
        contactDetails = new javax.swing.JPanel();
        photo = new javax.swing.JLabel();
        genderText = new javax.swing.JLabel();
        genderIcon = new javax.swing.JLabel();
        signDate = new javax.swing.JLabel();
        dateIcon = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        users = new javax.swing.JLabel();
        usersIcon = new javax.swing.JLabel();
        users_d = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        surname = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(820, 589));

        adminPanel.setBackground(new java.awt.Color(201, 197, 203));
        adminPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(215, 217, 215), 2, true));
        adminPanel.setPreferredSize(new java.awt.Dimension(820, 589));

        changePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePassword.setPreferredSize(new java.awt.Dimension(774, 72));
        changePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswordMouseClicked(evt);
            }
        });

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/password.png"))); // NOI18N

        passwordText.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        passwordText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordText.setText("Change your password");

        javax.swing.GroupLayout changePasswordLayout = new javax.swing.GroupLayout(changePassword);
        changePassword.setLayout(changePasswordLayout);
        changePasswordLayout.setHorizontalGroup(
            changePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passwordIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(passwordText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        changePasswordLayout.setVerticalGroup(
            changePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/profile.png"))); // NOI18N

        genderText.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        genderText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        genderText.setText("0");

        genderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/gender.png"))); // NOI18N

        signDate.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        signDate.setText("0");

        dateIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/date.png"))); // NOI18N

        dateText.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        dateText.setText("Join date:");

        users.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        users.setText("0");

        usersIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/users.png"))); // NOI18N

        users_d.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        users_d.setText("Users Registered:");

        javax.swing.GroupLayout contactDetailsLayout = new javax.swing.GroupLayout(contactDetails);
        contactDetails.setLayout(contactDetailsLayout);
        contactDetailsLayout.setHorizontalGroup(
            contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo)
                .addGap(18, 18, 18)
                .addGroup(contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contactDetailsLayout.createSequentialGroup()
                        .addGroup(contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(contactDetailsLayout.createSequentialGroup()
                                .addComponent(dateIcon)
                                .addGap(18, 18, 18)
                                .addComponent(dateText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signDate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contactDetailsLayout.createSequentialGroup()
                                .addComponent(usersIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(users_d)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(users, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 170, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactDetailsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(genderText, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genderIcon)))
                .addContainerGap())
        );
        contactDetailsLayout.setVerticalGroup(
            contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contactDetailsLayout.createSequentialGroup()
                        .addGroup(contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contactDetailsLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dateText)
                                    .addComponent(signDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addGroup(contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(users_d)
                                    .addComponent(users, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(contactDetailsLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(dateIcon)
                                .addGap(40, 40, 40)
                                .addComponent(usersIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contactDetailsLayout.createSequentialGroup()
                        .addGroup(contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(photo, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addGroup(contactDetailsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(contactDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(genderText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genderIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)))
                        .addContainerGap())))
        );

        firstname.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        firstname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstname.setText("0");

        surname.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        surname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        surname.setText("0");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addComponent(firstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(surname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(contactDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, 804, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseClicked
        PreparedStatement pst, pst2;
        String newPassword = JOptionPane.showInputDialog(null, "Enter a new password: ", "Input", JOptionPane.QUESTION_MESSAGE); //ask for new password
        while (!newPassword.isEmpty()) {
            try {
                PreparedStatement ps = getConnection().prepareStatement("SELECT email, password FROM register"); //query that retrieves email and password from the database
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    String user = rs.getString("password");
                    String decryptPassword = getDecodedPassword(user); //decoding the current password
                    if (newPassword.equals(decryptPassword)) {
                        ps.close();
                        rs.close();
                        newPassword = JOptionPane.showInputDialog(null, "This is the same password! Enter a new password: ", "Wrong Input", JOptionPane.WARNING_MESSAGE); //ask for input again if the pasword is the same
                    } else {
                        ps.close();
                        rs.close();
                        pst = getConnection().prepareStatement("UPDATE register SET password='" + getEncodedPassword(newPassword) + "' WHERE email='" + userName + "'"); //update password with the new encoded password retrieved from the input
                        pst.executeUpdate();
                        pst.close();
                        JOptionPane.showMessageDialog(null, "Password has been changed!");
                        break;
                    }
                } else {
                    ps.close();
                    rs.close();
                    pst2 = getConnection().prepareStatement("UPDATE register SET password='" + getEncodedPassword(newPassword) + "' WHERE email='" + userName + "'"); //update password with the new encoded password retrieved from the input
                    pst2.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Password has been changed!");
                    break;
                }
                getConnection().close();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(adminPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_changePasswordMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    public javax.swing.JPanel changePassword;
    public javax.swing.JPanel contactDetails;
    private javax.swing.JLabel dateIcon;
    private javax.swing.JLabel dateText;
    public static javax.swing.JLabel firstname;
    private javax.swing.JLabel genderIcon;
    public static javax.swing.JLabel genderText;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JLabel passwordText;
    private javax.swing.JLabel photo;
    public static javax.swing.JLabel signDate;
    public static javax.swing.JLabel surname;
    public static javax.swing.JLabel users;
    public static javax.swing.JLabel usersIcon;
    public static javax.swing.JLabel users_d;
    // End of variables declaration//GEN-END:variables
}
