/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import database.databaseConnection;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author Mahdi Islam - w1694532
 */
public final class dashboard3 extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashboard3
     */
    public JTextField text = new JTextField();

    public dashboard3() {
        initComponents();
        getChart();
    }

    public JFreeChart getChart() {

        JFreeChart chart = null;
        try {

            databaseConnection connection = new databaseConnection();

            String acronym = text.getText();

            String query = null;

            if (acronym.equals("")) {

                query = "Select projectAcronym , projectID  from dataset LIMIT 50  ";
            } else {

                query = "Select projectAcronym , projectID  from dataset WHERE projectAcronym LIKE '%" + acronym + "%' LIMIT 50";

            }

            JDBCCategoryDataset dataset = new JDBCCategoryDataset(databaseConnection.getConnection(), query);

            chart = ChartFactory.createLineChart("Chart", "Acronym", "ProjectID", dataset, PlotOrientation.VERTICAL, false, true, true);

            BarRenderer renderer = null;

            CategoryPlot plot = null;

            renderer = new BarRenderer();

        } catch (ClassNotFoundException | SQLException e) {
        }

        return chart;

    }

    public ChartPanel chartPanel;

    public JInternalFrame createGraph() {

        JInternalFrame frame = new JInternalFrame("Chart", true, true, true);

        try {

            JPanel panel = new JPanel();

            chartPanel = new ChartPanel(getChart());
            chartPanel.setPreferredSize(new Dimension(600, 300));

            JButton button = new JButton();

            button.setText("Update Graph");

            JLabel label = new JLabel();
            label.setText("Filter by Project Acronym");

            JPanel mainPanel = new JPanel();
            mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));

            JPanel paintPanel = new JPanel();

            paintPanel.add(chartPanel);
            JPanel textPanel = new JPanel();

            text.setPreferredSize(new Dimension(150, 30));
            textPanel.add(label);
            textPanel.add(text);
            textPanel.add(button);

            mainPanel.add(paintPanel);
            mainPanel.add(textPanel);

            panel.add(mainPanel);

            button.addActionListener((ActionEvent ae) -> {
                chartPanel.setChart(getChart());
                chartPanel.repaint();
            });

            frame.add(panel);
            frame.setVisible(true);

        } catch (Exception e) {
        }

        return frame;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        JInternalFrame frame1 = createGraph();
        jDesktopPane2.add(frame1);

        frame1.pack();
        frame1.setVisible(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    // End of variables declaration//GEN-END:variables
}
