/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import data.dateTime;
import static database.databaseConnection.getConnection;
import static database.databaseConnection.getUsers;
import static frames.adminPanel.firstname;
import static frames.adminPanel.genderText;
import static frames.adminPanel.surname;
import static frames.adminPanel.signDate;
import java.awt.event.MouseListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Beatrice Antoniu - w1688177
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     *
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public adminPanel adminPanel;
    public dashboard1 dashboard1;
    public dashboard2 dashboard2;
    public dashboard3 dashboard3;
    public main main;
    public static String userName;
    public static String getRole;

    public home(String username, String Role) throws SQLException, ClassNotFoundException {
        initComponents();
        name.setText(username);
        role.setText(Role);
        userName = username;  //logged in username
        getRole = Role; //logged in user role

        //display date and time
        dateTime.displayData();

        //display main dashboard template
        main = new main();
        body.add(main);
        main.setVisible(true);
        //set size to fit the desktop pane
        main.setSize(body.getWidth(), body.getHeight());
        //remove title bar
        BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane) ((BasicInternalFrameUI) main.getUI()).getNorthPane();
        main.remove(titlePane);
        //make frame
        BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) main.getUI());
        for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
            basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
        }
    }

    private static String getDecodedPassword(String password) {
        return new String(Base64.getMimeDecoder().decode(password));
    }

    //method to show personal details in the admin panel
    public static void showDataInAdminPanel(String username) throws ClassNotFoundException, SQLException {
        ResultSet rs;
        try (Statement s = getConnection().createStatement()) {
            rs = s.executeQuery("SELECT fname,surname,date,gender FROM register WHERE email='" + username + "'"); //query to retrieve certain data from database according to the user that's logged in
            if (rs.next()) {
                String fname = rs.getString("fname");
                String sname = rs.getString("surname");
                String getDate = rs.getString("date");
                String gender = rs.getString("gender");
                firstname.setText(fname);
                surname.setText(sname);
                signDate.setText(getDate);
                genderText.setText(gender);
            }
            s.close();
            getConnection().close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        role = new javax.swing.JLabel();
        graph1 = new javax.swing.JPanel();
        dash1_d = new javax.swing.JLabel();
        dash1 = new javax.swing.JLabel();
        graph2 = new javax.swing.JPanel();
        dash2_d = new javax.swing.JLabel();
        dash2 = new javax.swing.JLabel();
        graph3 = new javax.swing.JPanel();
        dsah3_d = new javax.swing.JLabel();
        dash3 = new javax.swing.JLabel();
        admin_panel = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        logout_panel = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        name_d = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        title = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        greeting = new javax.swing.JLabel();
        body = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Home");
        setResizable(false);

        background.setBackground(new java.awt.Color(180, 142, 174));

        menu.setBackground(new java.awt.Color(100, 110, 104));
        menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        role.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        role.setForeground(new java.awt.Color(215, 217, 215));
        role.setText("Employer");

        graph1.setBackground(new java.awt.Color(100, 110, 104));
        graph1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(215, 217, 215), 2, true));
        graph1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        graph1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graph1MouseClicked(evt);
            }
        });

        dash1_d.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        dash1_d.setForeground(new java.awt.Color(215, 217, 215));
        dash1_d.setText("Dashboard 1");
        dash1_d.setPreferredSize(new java.awt.Dimension(40, 15));

        dash1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/dash1.png"))); // NOI18N
        dash1.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout graph1Layout = new javax.swing.GroupLayout(graph1);
        graph1.setLayout(graph1Layout);
        graph1Layout.setHorizontalGroup(
            graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graph1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dash1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dash1_d, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        graph1Layout.setVerticalGroup(
            graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graph1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(dash1_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(graph1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dash1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        graph2.setBackground(new java.awt.Color(100, 110, 104));
        graph2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(215, 217, 215), 2, true));
        graph2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        graph2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graph2MouseClicked(evt);
            }
        });

        dash2_d.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        dash2_d.setForeground(new java.awt.Color(215, 217, 215));
        dash2_d.setText("Dashboard 2");
        dash2_d.setPreferredSize(new java.awt.Dimension(40, 15));

        dash2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/dash2.png"))); // NOI18N
        dash2.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout graph2Layout = new javax.swing.GroupLayout(graph2);
        graph2.setLayout(graph2Layout);
        graph2Layout.setHorizontalGroup(
            graph2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graph2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dash2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dash2_d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        graph2Layout.setVerticalGroup(
            graph2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graph2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(dash2_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(graph2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dash2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        graph3.setBackground(new java.awt.Color(100, 110, 104));
        graph3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(215, 217, 215), 2, true));
        graph3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        graph3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                graph3MouseClicked(evt);
            }
        });

        dsah3_d.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        dsah3_d.setForeground(new java.awt.Color(215, 217, 215));
        dsah3_d.setText("Dashboard 3");
        dsah3_d.setPreferredSize(new java.awt.Dimension(40, 15));

        dash3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/dash3.png"))); // NOI18N
        dash3.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout graph3Layout = new javax.swing.GroupLayout(graph3);
        graph3.setLayout(graph3Layout);
        graph3Layout.setHorizontalGroup(
            graph3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graph3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dash3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsah3_d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        graph3Layout.setVerticalGroup(
            graph3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, graph3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dsah3_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(graph3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dash3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        admin_panel.setBackground(new java.awt.Color(100, 110, 104));
        admin_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admin_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_panelMouseClicked(evt);
            }
        });

        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/admin.png"))); // NOI18N
        admin.setPreferredSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout admin_panelLayout = new javax.swing.GroupLayout(admin_panel);
        admin_panel.setLayout(admin_panelLayout);
        admin_panelLayout.setHorizontalGroup(
            admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        admin_panelLayout.setVerticalGroup(
            admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        logout_panel.setBackground(new java.awt.Color(100, 110, 104));
        logout_panel.setForeground(new java.awt.Color(215, 217, 215));

        time.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        time.setForeground(new java.awt.Color(215, 217, 215));
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("16:04");

        date.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        date.setForeground(new java.awt.Color(215, 217, 215));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("09/06/2020");

        name.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        name.setForeground(new java.awt.Color(215, 217, 215));
        name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        name.setText("James Brown");

        name_d.setFont(new java.awt.Font("Kristen ITC", 1, 13)); // NOI18N
        name_d.setForeground(new java.awt.Color(215, 217, 215));
        name_d.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_d.setText("Logged in as");

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logout.png"))); // NOI18N
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logout_panelLayout = new javax.swing.GroupLayout(logout_panel);
        logout_panel.setLayout(logout_panelLayout);
        logout_panelLayout.setHorizontalGroup(
            logout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logout_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logout_panelLayout.createSequentialGroup()
                        .addGroup(logout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logout))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logout_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(name_d)))
                .addContainerGap())
        );
        logout_panelLayout.setVerticalGroup(
            logout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logout_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name_d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(logout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logout_panelLayout.createSequentialGroup()
                        .addComponent(time)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date)
                        .addContainerGap())
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graph1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(graph2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(role)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(admin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(graph3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(role)
                    .addComponent(admin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(graph1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(graph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(graph3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(logout_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        title.setBackground(new java.awt.Color(201, 197, 203));
        title.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(215, 217, 215), 2, true));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/home.png"))); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        greeting.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        greeting.setForeground(new java.awt.Color(100, 110, 104));
        greeting.setText("Welcome");

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(greeting, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(greeting)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(body))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(body)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graph1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graph1MouseClicked
        //creating a new frame that calls the internal frame for the pie chart
        dashboard1 = new dashboard1();
        body.add(dashboard1);
        dashboard1.setVisible(true);

        //set size to fit the desktop pane
        dashboard1.setSize(body.getWidth(), body.getHeight());

        //remove title bar
        BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane) ((BasicInternalFrameUI) dashboard1.getUI()).getNorthPane();
        dashboard1.remove(titlePane);

        //make frame
        BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) dashboard1.getUI());
        for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
            basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
        }

        greeting.setText("Pie Chart");
    }//GEN-LAST:event_graph1MouseClicked

    private void admin_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_panelMouseClicked
        String askPassword = JOptionPane.showInputDialog("Enter your password: "); //require password to accesss admin panel
        while (!askPassword.isEmpty()) {
            try {
                PreparedStatement ps = getConnection().prepareStatement("SELECT password, role FROM register WHERE email=?"); //query to return what type of user has logged in
                ps.setString(1, login.username.getText());
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    String user = rs.getString("password");
                    String decryptPassword = getDecodedPassword(user); //decoding the password
                    if (!askPassword.equals(decryptPassword) && getRole.equals("Employer")) { //if password inserted is wrong for the Employer user ask for input again
                        JOptionPane.showMessageDialog(null, "ACCESS DENIED");
                        askPassword = JOptionPane.showInputDialog("Password is incorrect! Enter your password: ");
                    } else if (!askPassword.equals(decryptPassword) && !getRole.equals("Employer")) { //if password inserted is wrong for the Employee user ask for input again
                        JOptionPane.showMessageDialog(null, "ACCESS DENIED");
                        askPassword = JOptionPane.showInputDialog("Password is incorrect! Enter your password: ");
                    } else if (askPassword.equals(decryptPassword) && !getRole.equals("Employer")) { //if password inserted is correct for the Employee user create the new frame with the details that belong to the logged in user

                        ps.close();
                        rs.close();
                        adminPanel = new adminPanel();
                        body.add(adminPanel);
                        adminPanel.setVisible(true);

                        //set size to fit the desktop pane
                        adminPanel.setSize(body.getWidth(), body.getHeight());

                        //remove title bar
                        BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane) ((BasicInternalFrameUI) adminPanel.getUI()).getNorthPane();
                        adminPanel.remove(titlePane);

                        //make frame
                        BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) adminPanel.getUI());
                        for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
                            basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
                        }
                        adminPanel.users.setVisible(false);
                        adminPanel.usersIcon.setVisible(false);
                        adminPanel.users_d.setVisible(false);
                        JOptionPane.showMessageDialog(null, "ACCESS GRANTED");
                        greeting.setText("Admin Panel");
                        showDataInAdminPanel(userName);
                        break;
                    } else if (askPassword.equals(decryptPassword) && getRole.equals("Employer")) { //if password inserted is correct for the Employer user create the new frame with the details that belong to the logged in user
                        adminPanel = new adminPanel();
                        body.add(adminPanel);
                        adminPanel.setVisible(true);

                        //set size to fit the desktop pane
                        adminPanel.setSize(body.getWidth(), body.getHeight());

                        //remove title bar
                        BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane) ((BasicInternalFrameUI) adminPanel.getUI()).getNorthPane();
                        adminPanel.remove(titlePane);

                        //make frame
                        BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) adminPanel.getUI());
                        for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
                            basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
                        }
                        adminPanel.users.setVisible(true);
                        adminPanel.usersIcon.setVisible(true);
                        adminPanel.users_d.setVisible(true);
                        JOptionPane.showMessageDialog(null, "ACCESS GRANTED");
                        getUsers().toString();
                        showDataInAdminPanel(userName);
                        greeting.setText("Admin Panel");
                        break;
                    }
                } else { //if password is right on the first input
                    ps.close();
                    rs.close();
                    adminPanel = new adminPanel();
                    body.add(adminPanel);
                    adminPanel.setVisible(true);

                    //set size to fit the desktop pane
                    adminPanel.setSize(body.getWidth(), body.getHeight());

                    //remove title bar
                    BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane) ((BasicInternalFrameUI) adminPanel.getUI()).getNorthPane();
                    adminPanel.remove(titlePane);

                    //make frame
                    BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) adminPanel.getUI());
                    for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
                        basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
                    }
                    JOptionPane.showMessageDialog(null, "ACCESS GRANTED");
                    getUsers().toString();
                    showDataInAdminPanel(userName);
                    greeting.setText("Admin Panel");
                    break;
                }

                getConnection().close();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(adminPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_admin_panelMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        //closing connection to the database on logout
        try {
            getConnection().close();
            dispose();
            new login().setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        //creating a new frame that calls the internal frame for the main frame
        main = new main();
        body.add(main);
        main.setVisible(true);
        //set size to fit the desktop pane
        main.setSize(body.getWidth(), body.getHeight());
        //remove title bar
        BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane) ((BasicInternalFrameUI) main.getUI()).getNorthPane();
        main.remove(titlePane);
        //make frame
        BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) main.getUI());
        for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
            basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
        }

        greeting.setText("Welcome");
    }//GEN-LAST:event_homeMouseClicked

    private void graph2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graph2MouseClicked
        //creating a new frame that calls the internal frame for the bar chart
        try {
            dashboard2 = new dashboard2();
            body.add(dashboard2);
            dashboard2.setVisible(true);

            //set size to fit the desktop pane
            dashboard2.setSize(body.getWidth(), body.getHeight());

            //remove title bar
            BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane) ((BasicInternalFrameUI) dashboard2.getUI()).getNorthPane();
            dashboard2.remove(titlePane);

            //make frame
            BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) dashboard2.getUI());
            for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
                basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }

        greeting.setText("Bar Chart");
    }//GEN-LAST:event_graph2MouseClicked

    private void graph3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graph3MouseClicked
        //creating a new frame that calls the internal frame for the line chart
        dashboard3 = new dashboard3();
        body.add(dashboard3);
        dashboard3.setVisible(true);

        //set size to fit the desktop pane
        dashboard3.setSize(body.getWidth(), body.getHeight());

        //remove title bar
        BasicInternalFrameTitlePane titlePane = (BasicInternalFrameTitlePane) ((BasicInternalFrameUI) dashboard3.getUI()).getNorthPane();
        dashboard3.remove(titlePane);

        //make frame
        BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) dashboard3.getUI());
        for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
            basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
        }

        greeting.setText("Line Chart");
    }//GEN-LAST:event_graph3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new home(userName, getRole).setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JPanel admin_panel;
    private javax.swing.JPanel background;
    public static javax.swing.JDesktopPane body;
    private javax.swing.JLabel dash1;
    private javax.swing.JLabel dash1_d;
    private javax.swing.JLabel dash2;
    private javax.swing.JLabel dash2_d;
    private javax.swing.JLabel dash3;
    public static javax.swing.JLabel date;
    private javax.swing.JLabel dsah3_d;
    private javax.swing.JPanel graph1;
    private javax.swing.JPanel graph2;
    private javax.swing.JPanel graph3;
    private javax.swing.JLabel greeting;
    private javax.swing.JLabel home;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel logout_panel;
    private javax.swing.JPanel menu;
    public static javax.swing.JLabel name;
    private javax.swing.JLabel name_d;
    public static javax.swing.JLabel role;
    public static javax.swing.JLabel time;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
